### ISSUE TITLE
Niespójność harry_glowna.html - portrety

### ISSUE THREAD

**Issue by Hell4Ge** [Sonickers/potter#1]
Wchodzę na http://potter.nerfthis.xyz/harry_glowna.html

Klikam w Harrego i w innej zakładce otwiera mi się strona o Harrym,
klikam w Rona i w innej zakładce widzę jego zdjęcie

To jest na ten moment nieintuicyjne, spodziewam się, że kliknięcie na każdy z tych obrazków wywoła taką samą akcję (albo wyświetli mi zdjęcie, albo przejdę na osobną stronę z informacjami o danej postaci)

W takich sytuacjach należy dać znać użytkownikowi, że dany element jest jeszcze in progress. Zakładając, że jedynie Harry jest działający, reszta postaci powinna mieć szary portret a po kliknięciu na nie nic nie powinno się dziać (kursor myszy też nie powinien sugerować, że dany obrazek można kliknąć).

**Comment by Sonickers** [comment]
Słuszna racja :D

**Comment by Sonickers** [comment]
Się robi!
